services:
  - name: whatsapp-support-bot
    type: web
    instance_types:
      - type: nano
    regions:
      - fra
    env:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
    ports:
      - port: 3000
        protocol: http
    checks:
      - type: http
        path: /health
        port: 3000
        interval: 30s
        timeout: 10s
        grace_period: 10s
    scaling:
      min: 1
      max: 1
    docker:
      dockerfile: Dockerfile
    volumes:
      - name: wwebjs-auth
        path: /app/.wwebjs_auth
        size: 1GB
